development:
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
  database: pinatra_development

test:
  adapter: mysql2
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
  database: pinatra_test